### ISSUE TITLE
CC2 install instructions do not quite work 

### ISSUE THREAD

**Issue by dalexander** [PacificBiosciences/unanimity#15]
pip commands seem incorrect

```
(VE) [~/Sources/git/unanimity]$ pip install --update --no-deps -r requirements.txt

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --update
```

I don't think you want the options on this pip command.  I think you just want `pip install -r requirements.txt`.

**Comment by armintoepfer** [comment]
I've split your two issues, to address them separately

**Comment by armintoepfer** [comment]
There is a typo in the INSTALL, should be `--upgrade` instead of `--update`. It was meant to ease install, but it caused more trouble. Ok, let's get rid of this file.  https://github.com/PacificBiosciences/unanimity/pull/17
